
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "4300:4300"
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=aaa...000
      - MYSQL_DATABASE=test
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: aaa...000
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge